ucsb-cs148-w25/pj14-lootfinder

teams/Awin.md
Reverts ucsb-cs148-w25/pj14-lootfinder#7
=> Revert "Create Awin.md"

teams/sprint01/lec02.md
Markdown file for Lect02 Meeting
=> Stand up Meeting for 1/13/25

LootFinder/.prettierrc, LootFinder/package-lock.json, LootFinder/package.json
Closes #38 
In this PR, we
1. Add Prettier as a dependency
2. Add a Prettier config file
3. Add a script that runs Prettier on the source files
=> 38 - Add Prettier Configuration

LootFinder/src/App.vue, LootFinder/src/components/Navbar.vue, LootFinder/src/router/index.ts, LootFinder/src/views/CreateOffer.vue, LootFinder/src/views/Home.vue
Closes #46 
Adding a navbar and create offer page
Doesn't good right now, but we can build on top of it
=> 46 - Create Offer Page and Navbar

LootFinder/src/views/Login.vue
Closes #81 
- A new document is created for each unique user, using their uid as the document id
- Checks if there already exists a document for the user, if so, nothing happens.
=> Create A User Document for each User at Login

LootFinder/src/components/Navbar.vue, LootFinder/src/components/OfferCard.vue, LootFinder/src/router/index.ts, LootFinder/src/views/BrowseOffers.vue
=> 51 - Add offer cards and browser offers page

LootFinder/src/components/Navbar.vue
changed navbar to show correct profile picture when logged in, and a log-in button when not logged in.
=> changed navBar

LootFinder/src/firebase.ts, LootFinder/src/views/CreateOffer.vue, LootFinder/src/views/Login.vue
Closes #47 
- When form is submitted, a new document is added to the firestore collection named 'offer'. 
- The document has a field called 'sellerId' that references the user who submitted the form
- There is a new document in a sub-collection of the author's user document called 'offers' that stores documents that contain references to offers they made.
=> Connect Create Form to Backend Firestore

LootFinder/src/components/Navbar.vue
The mobile menu actually works now
=> Make mobile menu work

LootFinder/src/components/Navbar.vue, LootFinder/src/router/index.ts, LootFinder/src/views/UpdateOffers.vue
- Users can select an option to edit any of their existing listings.
- An editable form pre-populated with the existing listing data appears when editing.
- After making changes, users can save updates, which are then reflected in Firebase Firestore.
- Users receive a confirmation message upon successful update.
Closes #49
Note: To test, pull and run branch locally. Then, create an offer for your user profile and you should be able to see it in the "My Offers" page. Then, you can test editing the offers from there and see it reflect in Firestore database.
=> Listing User Offers and allowing them to Update/Edit their offers

LootFinder/index.html, LootFinder/src/App.vue, LootFinder/src/components/Footer.vue
Closes #95 
Added footer to each page:
Also updated the app title and favicon:
=> Add Footer and also changed app title and favicon

LootFinder/src/components/OfferCard.vue, LootFinder/src/views/BrowseOffers.vue, team/sprint02/lec06.md
=> fetch offers from backend (needs polishing)

LootFinder/src/views/BrowseOffers.vue
Closes #54 
In this PR, we add a frontend filter by title and min/max price
=> 54 frontend filter implementation

team/MVP_FOLLOWUP.md
added mvp follow-up file for lab5
=> MVP follow-up file

LootFinder/package-lock.json, LootFinder/package.json, LootFinder/tests/BrowseOffers.spec.js, LootFinder/vitest.config.js, team/TESTING.md
In this PR, we add the testing framework vitest to our project and create a unit test for a frontend component.
Closes #114
=> Add Unit Testing

LootFinder/src/views/BrowseOffers.vue, LootFinder/src/views/UpdateOffers.vue
=> Mark as sold implemented

LootFinder/src/components/OfferCard.vue, LootFinder/src/router/index.ts, LootFinder/src/views/ChatView.vue
This PR adds the frontend messaging components. Will be connected to the backend (firebase firestore) in a future PR.
- Added a "Message Seller" button that, when clicked on, takes user to a page where they can chat with the seller.
Closes #110
=> Adding Messaging Frontend

LootFinder/package-lock.json, LootFinder/package.json, LootFinder/src/App.vue, LootFinder/src/components/InputMap.vue, LootFinder/src/components/OfferForm.vue, LootFinder/src/config.ts, LootFinder/src/style.css, LootFinder/src/views/CreateOffer.vue
- Refactored Create Offer view, now there is OfferForm vue component, which is imported in CreateOffer view
- InputMap component for the map that is used in OfferForm.vue component
- Styling changes to Offer Form
- Drop and Drag Image for the image uploading
- Checks for location input, if none, the form is not submitted and user is redirected to form to input a location.
Closes #103
=> Added Map component to Offer Form

LootFinder/package.json, LootFinder/tests/OfferCard.spec.js, team/TESTING.md
Closes #151
In this PR, we add testing for the OfferCard component.
=> 151 Component Testing

LootFinder/src/views/Home.vue
- Changed lorem ipsum text
- Redirected "try it out link"
- Changed theme colors
- Fixed "get started" button to direct logged in users to browse offers
Closes #137
=> Hero Page updates

LootFinder/src/components/Navbar.vue
- Added bg color to mobile navbar
- Clickable profile directory
- Mobile navbar now appears in home page
- Matched shape of other clickable directories
Closes #146
=> Fixed mobile navbar

LootFinder/src/views/ChatView.vue
This PR makes the message bubbles prettier and also adds timestamps to them.
Before:
After:
Closes #157
=> Cleaning up Messages Bubbles/Adding Timestamps

LootFinder/.gitignore, LootFinder/src/config.ts
=> Env file change

LootFinder/src/components/BrowseMap.vue, LootFinder/src/views/BrowseOffers.vue
Closes #142 
Features:
- The map displays every Filtered Item as a Marker
- Upon clicking on a marker, an additional OfferCard is shown on the right side of the map showing information of that item, as well as centering the map
=> Add BrowseMap to BrowseOffers

LootFinder/src/components/InputMap.vue
Closes #143
New button on the map that allows for user to center the map on their location.
=> Add Centering Functionality to Map on Create Form

LootFinder/src/components/AIDisclaimerModal.vue, LootFinder/src/components/BountyCard.vue, LootFinder/src/components/BountyForm.vue, LootFinder/src/firebaseService.ts, LootFinder/src/router/index.ts, LootFinder/src/views/BrowseBounties.vue, LootFinder/src/views/CreateBounty.vue, LootFinder/src/views/CreateOptions.vue, LootFinder/src/views/Inbox.vue
In this PR, we implement bounties
=> Bounty Implementation

LootFinder/src/components/Navbar.vue, LootFinder/src/components/OfferForm.vue
Closes #176 
Bye bye dashboard
=> Remove dashboard from navbar and reroutes, but kept the page alive

LootFinder/src/components/OfferForm.vue
Added validation to ensure there is an image, title, description and price > 0 for every offer created.
Closes #173
=> Form Field Validation

LootFinder/src/views/BrowseOffers.vue
=> admin back online

LootFinder/src/components/Navbar.vue, LootFinder/src/views/ChatView.vue, LootFinder/src/views/Inbox.vue
This PR adds an indicator/notification for alerting users when they receive new messages in their inbox.
When user receives new messages:
After they open their inbox (number goes away):
Closes #60
=> Add Notification Indicator for New Messages

LootFinder/src/components/DistanceFilterPopup.vue, LootFinder/src/views/BrowseOffers.vue
Closes #182 
New button "Filter by distance"
Which brings up this popup:
Afterwards it will filter out only offers within the radius:
=> Filter by distance

LootFinder/src/App.vue, LootFinder/src/components/BountyCard.vue, LootFinder/src/components/BrowseMap.vue, LootFinder/src/components/BrowseViews/OffersView.vue, LootFinder/src/components/DistanceFilterPopup.vue, LootFinder/src/components/Navbar.vue, LootFinder/src/components/OfferCard.vue, LootFinder/src/components/OfferForm.vue, LootFinder/src/style.css, LootFinder/src/views/Browse.vue, LootFinder/src/views/CreateOptions.vue, LootFinder/src/views/Home.vue, LootFinder/src/views/Inbox.vue, LootFinder/src/views/Login.vue, LootFinder/src/views/UpdateOffers.vue, LootFinder/src/views/UserProfile.vue
=> Styling Changing
